### ISSUE TITLE
Team31 Review: Traceability Issues & Cause of Failure H4-1

### ISSUE THREAD

**Issue by EthanVinceBudan** [marlon4dashen/Hairesthetics#10]
Here are my recommended edits:
- I believe the traceability information in this document has been done incorrectly. The "SR" and "Ref" categories in the FEMA table are used to connect safety requirements to hazards, not FRs to hazards. Currently it is difficult to tell which hazards are the cause behind which safety requirement(s) which will make future changes difficult to manage.
- The cause of failure stated for H4-1 (cannot login) seems more like an intended feature of the system, rather than an unexpected issue. In my opinion the cause could be better attributed to either connectivity issues with the authentication system, or the user forgetting their credentials.

**Comment by marlon4dashen** [comment]
Thanks for your comment, this issue is resolved in the above PR!
