### ISSUE TITLE
Team 15 Review: Role of Admin

### ISSUE THREAD

**Issue by yazdinip** [marlon4dashen/Hairesthetics#11]
Had a hard time understanding the role of Admin and Supervisor. Its mentioned to some extend in the Access requirements (ACR), however none of those requirements are mentioned in the FMEA table, causing further confusion. It seems as if the role of the admin is to enable extra functionality in which case, it's acting as an unnecessary extra actor and a potential hazard. 

@samm82

**Comment by marlon4dashen** [comment]
Thanks for your comment, this issue is resolved in the above PR!
