### ISSUE TITLE
Team 15 Review: Data Hazards

### ISSUE THREAD

**Issue by yazdinip** [marlon4dashen/Hairesthetics#12]
In my opinion, the main risks in this scenario are associated with data hazards, both online and offline. As such, I find it important to further identify hazards in some of the extra safety functionalities such as daily uploads or data caching in case of no connection. Naturally, some of these hazards might be out of scope, especially with cloud storage and API's.

@samm82

**Comment by marlon4dashen** [comment]
Thanks for your comment, this issue is resolved in the above PR!
