### ISSUE TITLE
Team 15 Review: Recommended Action Methodology

### ISSUE THREAD

**Issue by Adham-Badawy** [marlon4dashen/Hairesthetics#13]
Hey guys, for your FMEA table, I noticed a trend in a lot of your recommended actions that I think you should fix to improve your FMEA. Ill explain with an example:

Your first failure mode for the Facial Recognition System is that "The facial landmarks aren't computed correctly". Your recommended action for this is to "Ask the user for input again".

My issue with this kind of recommended action is that it only covers what to do in case of this failure mode occurring, and NOT how to avoid it or keep it from occurring. Could you perhaps include a check that computes the facial landmarks multiple ways or multiple times and only moves ahead if all the iterations agree within some tolerance to avoid incorrect computations? I find this pattern occurs with many of your other failure modes as well.

The way I see it, the point of the Hazard analysis is to think about possible failure modes, then attempt to add functionality/design your program to avoid or eliminate those hazards first, and THEN if there's no way to reliably do that, then you start worrying about mitigation strategies to reduce the impact when they do happen. 

I'm missing a lot of domain specific knowledge here, so its possible there is no way to eliminate or avoid any of the hazards you mention, but I think it's worth you guys looking into it

@samm82

**Comment by Niu0351** [comment]
Issue resolved with the latest revision
