### ISSUE TITLE
Team 15 Review: Facial recognition hazard

### ISSUE THREAD

**Issue by jandricd** [marlon4dashen/Hairesthetics#14]
An issue I see is with H1-1, how would you determine that the facial landmarks are not computed properly, and who would be responsible for determining if they aren't computed properly? I think this hazard would make more sense as: "the facial landmarks cannot be computed", as it's easy to measure. The mitigation here would also be the same.
@samm82

**Comment by Niu0351** [comment]
Issue resolved
