### ISSUE TITLE
Team31 Review: H1-2 Issues

### ISSUE THREAD

**Issue by collinkan** [marlon4dashen/Hairesthetics#16]
- A lot of the recommended actions don't directly mitigate or eliminate the specified hazards. Instead, they pass along the responsibility to the user or simply notifies the user. Recommended action should be an area where you specify what you, as the developer, can do. This was mentioned extensively by my other teammates, but "ask user for input again", or "inform user to try again" does not really solve the underlying problem. 

- H1-2 is pretty vague, the application crashes because of model execution failure, but why would the model execution fail in the first place? This also ties back into my first point where your recommended action doesn't really help to fix this hazard. Also, Failure Mode and Effects of Failure are essentially the same thing.

- As mentioned by @EthanVinceBudan the traceability of the FMEA table is either done incorrectly or not very easy to follow. I'm not sure what RAR1 is, or how it relates to H1-2

**Comment by Niu0351** [comment]
Issue fixed
