### ISSUE TITLE
Team 14 Review (VnV Plan): Functional Requirements - Hair Modification System

### ISSUE THREAD

**Issue by AndrewBalmakund** [marlon4dashen/Hairesthetics#18]
There should be a test to check if a camera can be accessed. In addition, further tests for non-functional requirements would be to assess the overall quality of the camera in case of a situation where the camera is not able to focus properly or if the camera lens has scratches, the system may be confused and interpret something differently. 

Name: Andrew Balmakund
Student No: 400182420
Mac Id: balmakua

**Comment by billsong0407** [comment]
Thank you for reviewing our VnV plan! Having access to the camera is one of the prerequisites and this system takes an image or video as input. In addition, we do have test cases on bad-quality images and images without a person.
