### ISSUE TITLE
Team 14 Review (VnV Plan): SL-T2 / SL-T3

### ISSUE THREAD

**Issue by brandonduong** [marlon4dashen/Hairesthetics#19]
It is specified how the test will be performed, but what is the success criteria for these? I.e what is the maximum amount of times the response time is > 1 second for the test to be categorized as a pass?

**Comment by brandonduong** [comment]
@CSchank

**Comment by brandonduong** [comment]
Name: Brandon Duong
macId: duongb9
Student #: 400210462

**Comment by xuq37** [comment]
The success criteria is indicated in "how test will be performed session for each test case"
