### ISSUE TITLE
Team 14 Review (VnV Plan): Suggestions for 4.6 - Automated Testing and Verification Tools

### ISSUE THREAD

**Issue by mihail-serafim** [marlon4dashen/Hairesthetics#20]
Although I thought your section 4.6 was well done and is a complete set of tools, I had some ideas while reading through it that might be useful for increased readability. As someone not closely familiar with XCode, I was first uncertain as to how test coverage would be implemented in the iOS code. Also, I know that Postman has automation for testing, but many are familiar with it as a manual testing tool so it might be good to briefly discuss coverage and automation overall.

Name: Mihail Serafimovski
Student No: 400269483
Mac Id: serafimm

**Comment by billsong0407** [comment]
Thanks for your comments!
