### ISSUE TITLE
Team 14 Review (VnV Plan): Should include a complete survey

### ISSUE THREAD

**Issue by AndrewBalmakund** [marlon4dashen/Hairesthetics#22]
Although there are survey questions in the non-functional requirements, there should be a way to better gauge the answers that the user provides by having a complete survey. Meaning, asking more than one question for each non-functional requirement will enhance the overall feedback provided by the user. 

Name: Andrew Balmakund
Student No: 400182420
Mac Id: balmakua

**Comment by marlon4dashen** [comment]
This is fixed.
