### ISSUE TITLE
Team 13 Review: Design Document - Hardware Hiding Modules in MG

### ISSUE THREAD

**Issue by faiq-bokhari** [marlon4dashen/Hairesthetics#40]
Hey everyone, great job on the documents. They seem very detailed and easy to understand. I just have a suggestion regarding your hardware hiding modules in the MG. I think it would be good to go into a little more detail for the camera usage and maybe specify the specific hardware that is being used so it is not interpreted as a broader camera access module. 

@tingyuw

**Comment by marlon4dashen** [comment]
We have included more details in the latest revision, thanks!
