### ISSUE TITLE
Team31 Review: Broad Causes of Failures in FMEA Table

### ISSUE THREAD

**Issue by atunney** [marlon4dashen/Hairesthetics#6]
2 of your failure modes (Failed to load hairstyle models and Failed to compute recommendations, Invalid
user input) list the causes of failure as 'Database Failure'. Perhaps this could be elaborated on as to _what_ part of the database is failing or why it's failing so the hazard can be more easily resolved or mitigated if it were to occur.

**Comment by marlon4dashen** [comment]
We have decided to remove the use of database in our latest revision, this can be closed.
