### ISSUE TITLE
Team12 Review: [VnV Report] Changes made are vague

### ISSUE THREAD

**Issue by YoussefRizkalla** [marlon4dashen/Hairesthetics#67]
Section 7 states that some "bugs, errors and accessibility issues" were identified and resolved, but does make any mention of any specific issues, how the VnV process helped identify those or the approach that was taken to fix them.

CC: @CSchank

**Comment by Niu0351** [comment]
Resolved, specific and elaborate information in section 7 Changes Due to Testing is provided.
