### ISSUE TITLE
Team12 Review: [VnV Report] Automated testing 

### ISSUE THREAD

**Issue by YoussefRizkalla** [marlon4dashen/Hairesthetics#68]
The automated testing section makes mention of some technologies, but does not discuss how they were actually used in the VnV process. Additionally, some of the tooling mentioned is not actually automated (i.e. style guides, postman and chrome devs tools; these are traditionally manual tools used by developers).

CC: @CSchank

**Comment by xuq37** [comment]
Issue solved by changing the name of section 8.
