### ISSUE TITLE
Team31 Review: Hazard Analysis Review

### ISSUE THREAD

**Issue by harsh2204** [marlon4dashen/Hairesthetics#7]
The FMEA table is lacking depth and additional traceability information for the given set of components. The list of components and their failure modes is well captured, however some details could be improved upon.

For example, in `H2-1`, the only cause of failure is database, which leaves out any local causes of failure like an incomplete download or corrupt model file on the device. Moreover, the SR lists `HM6` which uses the word `dataset` only to represent what I'm assuming is the model. This failure mode also relates to `FR-4` more broadly which is missing in the SR altogether.

Finally, I'm not sure about `Asking the user for input again` as a recommended action against more that one of these failure modes. This leaves the user clueless on whether the issue is user or system-sided, if the app keeps asking the user for some input.

**Comment by marlon4dashen** [comment]
Thanks for your comment, this issue is resolved in the above PR!
