### ISSUE TITLE
Team12 Review: [VnV Report] Section 7 is contradictory

### ISSUE THREAD

**Issue by YoussefRizkalla** [marlon4dashen/Hairesthetics#70]
Section 7 mentions that the API endpoint / backend unit tests identified errors and bugs in the application. However, this is contradictory to the other sections in the document, as all tests are reported as passing. If there were no failing tests, how could they be used to identify bugs and errors?

CC: @CSchank

**Comment by Niu0351** [comment]
Updated for some failed tests, issues are mentions in section 7 as well
