### ISSUE TITLE
Team 12 Review: [VnV Report] Survey results are missing

### ISSUE THREAD

**Issue by Tamas-Leung** [marlon4dashen/Hairesthetics#71]
For some tests, there exists a survey to receive feedback from users, such as EU-T1. The test report does not include any results or any analysis based on the results received. 

CC: @CSchank

**Comment by xuq37** [comment]
Unfortunately, the surveys were not recorded, therefore it is not able to be presented on paper. We did provide scenarios to discribe the  survey.
