### ISSUE TITLE
Team 12 Review: [VnV Report] Reflection does not answer the required questions

### ISSUE THREAD

**Issue by Tamas-Leung** [marlon4dashen/Hairesthetics#72]
The reflection is missing answers for the required question. See https://github.com/smiths/capTemplate/blob/cde94719e393750e0148ac53d3f6bd5a9ab395d6/docs/VnVReport/VnVReport.tex#L108
to see the question.

@CSChank

**Comment by Niu0351** [comment]
General Reflection according to required questions are added on the report
