### ISSUE TITLE
Team31 Review: Ambiguity in safety and security requirements

### ISSUE THREAD

**Issue by Zhu-K** [marlon4dashen/Hairesthetics#8]
Good analysis overall but some of the safety and security requirements are a little vague and can be more descriptive.

For example, under 6.0.2, IR1 states "modify data unnecessarily", what is the data in question and what constitutes "unnecessarily"? Similarly, IR3 ("Data will be automatically backed up daily") leaves one questioning what sort of data? All data or just some data? Are we talking about backing up local user data on their devices, or server-side data on cloud storage?

@tomashetMcMaster

**Comment by marlon4dashen** [comment]
Thanks for your comment, this issue is resolved in the above PR!
