### ISSUE TITLE
Team31 Review: Splitting Failure Modes and Better Recommended Actions 

### ISSUE THREAD

**Issue by chrisandrade716** [marlon4dashen/Hairesthetics#9]
A couple of things I'd like to comment on regarding the hazard analysis document:

- The row with the cause of failure as "User might not input proper image/video" should probably be split into two separate failure modes. The user could input a corrupted image/video/of the incorrect format (.mp4, etc), OR they could input a totally fine photo/video but it's overly complicated (too much background involvement/too many faces, etc). And the recommended action, as explained in @harsh2204's Git Issue, could probably be improved now after splitting the two modes, instead of over-generalizing the modes and the action to just asking for new input.
- In the case of database failures, I don't think it's quite right to simply ask the user to attempt again or just reboot. As @atunney said in their Git Issue, the cause of failure in the chart should be more clear than just a database failure, and to elaborate on that, the recommended action should also be more clear; notify the user _specifically_ why their inputs are failing (notify them that there is a database failure and if its user-related or not), instead of just asking them to attempt again or suddenly rebooting which may change nothing if the issue stems from the database host

**Comment by marlon4dashen** [comment]
Thanks for your comment, this issue is resolved in the above PR!
